### ISSUE TITLE
Implement Human Pet

### ISSUE THREAD

**Issue by traaks** [traaks/echopet#2]
While the human pet interfaces are currently available, there is no implementation for them. Additionally the single equipment item may be outdated. The full set of equipment items may be usable instead. Furthermore, due to the lack of an implementation of both [IHumanPet](https://github.com/traaks/echopet/blob/master/src/com/dsh105/echopet/compat/api/entity/type/pet/IHumanPet.java) and [IEntityHumanPet](https://github.com/traaks/echopet/blob/master/src/com/dsh105/echopet/compat/api/entity/type/nms/IEntityHumanPet.java), the following exception is thrown when the plugin is enabled:
```
Caused by: java.lang.ClassNotFoundException: com.dsh105.echopet.compat.nms.v1_9_R1.entity.type.EntityHumanPet
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372) ~[?:1.8.0_05]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.8.0_05]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_05]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360) ~[?:1.8.0_05]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.9.jar:git-Spigot-87e2f47-94ba824]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.9.jar:git-Spigot-87e2f47-94ba824]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_05]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_05]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_05]
	at java.lang.Class.forName(Class.java:259) ~[?:1.8.0_05]
	at com.dsh105.echopet.compat.api.util.Reflect.getClass(Reflect.java:47) ~[?:?]
	at com.dsh105.echopet.compat.api.entity.PetType.<init>(PetType.java:79) ~[?:?]
	at com.dsh105.echopet.compat.api.entity.PetType.<clinit>(PetType.java:70) ~[?:?]
	... 12 more
```
And when the plugin is disabled:
```
java.lang.NoClassDefFoundError: Could not initialize class com.dsh105.echopet.compat.api.entity.PetType
	at com.dsh105.echopet.EchoPetPlugin.onDisable(EchoPetPlugin.java:99) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:293) ~[spigot-1.9.jar:git-Spigot-87e2f47-94ba824]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:364) [spigot-1.9.jar:git-Spigot-87e2f47-94ba824]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [spigot-1.9.jar:git-Spigot-87e2f47-94ba824]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417) [spigot-1.9.jar:git-Spigot-87e2f47-94ba824]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.disablePlugins(CraftServer.java:340) [spigot-1.9.jar:git-Spigot-87e2f47-94ba824]
	at net.minecraft.server.v1_9_R1.MinecraftServer.stop(MinecraftServer.java:454) [spigot-1.9.jar:git-Spigot-87e2f47-94ba824]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:595) [spigot-1.9.jar:git-Spigot-87e2f47-94ba824]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_05]
```

**Comment by traaks** [comment]
Human pets should work decently now. See https://github.com/traaks/echopet/commit/f048ed0fcf061fe699173152ab32bc2ec84fcd49, https://github.com/traaks/echopet/commit/de3aad8597c23b6bd434314e5d2d1009e5a9fc89 and https://github.com/traaks/echopet/commit/e5ce4fc8f754622bb65a48e3ed1da24cd1ac68cf.
